export const Emojis = {
    TIMER: "⌛",
    PING_PONG: "🏓",
    DANGER: "🚫",
    MUSIC: "🎶",
    SEARCH: "🔎",
    SUCCESS: "👍",
    SAD: "😔",
    PLAY: "▶️",
    PAUSE: "⏸️",
    WAVE: "👋",
    REPEAT: "🔄",
    SINGLE_REPEAT: "🔂",
    TICK: "✅",
    CROSS: "❌",
    INFO: "🔖",
    SOUND: "🔊",
    PAGE: "📄",
    WHITE_FLOWER: "💮",
    SYSTEM: "💻",
    BOT: "🤖",
    CHAIN: "⛓️",
    PAPER_PENCIL: "📝",
    HEART: "❤️",
    EIGHTBALL: "🎱",
    THINKING: "🤔",
    CAMERA: "📷",
};
